language: csharp
mono: none
dotnet: 3.1.401
sudo: required
env:
    global:
        - ASPNETCORE_ENVIRONMENT=Production
        - PGPORT=5433
        - PGVER=12
addons:
  postgresql: '12'
  apt:
    packages:
    - rabbitmq-server
    - postgresql-12
    - postgresql-client-12
services:
    - docker
    - rabbitmq
    - redis 
branches:
    only:
        - master
before_script:
    - chmod -R a+x scripts
    - psql -c 'create database subscriptions;'
    - psql -c "alter user postgres password 'postgres';"
script:
    - './scripts/create-nuget-config.sh $MYGET_KEY'
    - './scripts/dotnet-test.sh'
    - './scripts/travis-build.sh'
after_success:
    - './scripts/travis-docker-publish.sh'
subscriptions:
    email: false
    slack:
        secure: YMwRkX1T4hO7R3+31dMPNSG9L3vpLfkY0+aAfenUPWTZKZgcrA/tt8wAu3lD9F17ZRssCdtyv0ipJzPMNVw+J3PQSjuS+0AoB3KF8EUo5tSPcpT430+eg+FENmeII4kRqwiJSYjJ3enJXRO2lVLT6s9zAJJW8Y/VZKWHbQDSMLwonnTWy61VOIaLf6JllmVmjS8URsAyAfiguMIi7mc1D5YJhuiA8g5UcAPZMcNjzAB+C+Ewy+8OHTjUDOP7zKwXZ7XzG25wSshUQaDUZk+7Kz75zD0Q5lTlj7vKNaz101/zXeFrxApqZzaqUvI8QiXE8dk+hBut/kZE9czCsgBU4/yvjZ8pb6Oo5OOHVASlvT9N8MgIQKkJtwW7O20YcPgZeIcinngt1v3bKqSkUIxevJxRyhk4sGmp92MRseajfziH2PLER3aFsO+rsVLGXnD0dTEQUyqL2APmQ4awKGaPUW5SQ09i6sF8ZbKZvyZ/P3XtWv5mhDYA0KHRJ4oYv79ZBWWCHoZtzQpALerDvO8YRDaI86XxzqzxEZgk5L4gK24Jnc/yi/tRlRgrnd/KE0i3SF/U0yDpFw6F+4ZeDfcbpdC4a05nvH4GJTQUSq0NGqNw7ptfzT4zFwWhP1VPf1OEEwrfxOgCG5N/6QEBCuZZ8PoDtzziAM1W9C0JELfDezY=
        on_pull_requests: false
